---
# tasks file for chrony
- name: S assurer que le package chrony est installe 
  dnf:
    name: chrony
    state: present 

- name: Esnure Chrony is configured 
  template:
    dest: /etc/chrony.conf 
    src: chrony.conf.j2
  notify: restart_chrony

- name: Ensure Chrony is started 
  service:
    name: chronyd
    state: started 
